### ISSUE TITLE
package.json should be optional in a gulp environment

### ISSUE THREAD

**Issue by simonzack** [thlorenz/browserify-shim#136] opened 2015-02-11 21:38 UTC
In a gulp environment, it's much more natural to do:

    var shim = require('browserify-shim');
    browserify().transform(shim, {jquery: ...})....

instead of putting everything in package.json. Can this be an option?

**Comment by bendrucker** [comment] 2015-02-11 22:38
Duplicate of #65. We'll review a PR but it's a low priority so there's no plan to add this.

**Closed by bendrucker** 2015-02-11 22:38 UTC
