### ISSUE TITLE
Implementing History.js with browserify

### ISSUE THREAD

**Issue by melbourne2991** [thlorenz/browserify-shim#159] opened 2015-04-21 05:44 UTC
I am trying to implement history.js which is in itself a shim/wrapper for older browsers.

It's dependencies are as follows

(function(window,undefined){
	"use strict";

	// --------------------------------------------------------------------------
	// Initialise

	// Localise Globals
	var
		console = window.console||undefined, // Prevent a JSLint complain
		document = window.document, // Make sure we are using the correct document
		navigator = window.navigator, // Make sure we are using the correct navigator
		amplify = window.amplify||false, // Amplify.js
		setTimeout = window.setTimeout,
		clearTimeout = window.clearTimeout,
		setInterval = window.setInterval,
		clearInterval = window.clearInterval,
		JSON = window.JSON,
		alert = window.alert,
		History = window.History = window.History||{}, // Public History Object
		history = window.history; // Old History Object

How can I integrate it properly and then use window.History as per normal?

**Comment by bendrucker** [comment] 2015-04-21 11:24
Please share what you've tried thus far and what's not working

**Comment by neurosnap** [comment] 2015-04-28 19:26
https://github.com/Raynos/html5-history

Does all the work for you, but just as a warning, html4 support is disabled by default.

**Comment by thlorenz** [comment] 2015-04-29 17:07
@neurosnap that's a great alternative, however doesn't answer the question regarding shimming `history.js`.
@melbourne2991 any news on a sample project?

Let us know if you lost interest possibly due to the presented alternative so we can close this issue. Otherwise please provide us with a way to reproduce your problem in a separate github project.

**Comment by melbourne2991** [comment] 2015-05-13 15:19
@thlorenz Lost interest for other reasons, can close this @thlorenz cheers

**Closed** 2015-05-13 18:53 UTC
Labels: awaiting response
