### ISSUE TITLE
Allow complete encapsulation of shimmed modules

### ISSUE THREAD

**Issue by Kha** [thlorenz/browserify-shim#151] opened 2015-03-29 09:37 UTC
I would appreciate an option to replace `global/window` with a local object set up by browserify-shim so that imports and exports do not escape into the global scope. Afaik, webpack does something like this.

**Comment by thlorenz** [comment] 2015-03-29 14:31
Duplicate of #137.

**Closed by thlorenz** 2015-03-29 14:31 UTC
